dotenv: .env

dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.6.1
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.6.1"
networks:
  default: development

  development:
    gas_lane: "0x474e34a077df58807dbe9c96d3c009b23b3c6d0cce433e59bbf5b34f823bc56c" # 30 gwei
    update_interval: 30
    raffle_entrance_fee: 0.01 # 0.01 ETH
    callback_gas_limit: "2500000" # 2,500,000 gas
    verify: False

  sepolia:
    subscription_id: 1951
    update_interval: 30
    gas_lane: "0x474e34a077df58807dbe9c96d3c009b23b3c6d0cce433e59bbf5b34f823bc56c" # 30 gwei
    raffle_entrance_fee: 0.01 # 0.01 ETH
    callback_gas_limit: "2500000" # 2,500,000 gas
    vrf_coordinator_v2: "0x8103b0a8a00be2ddc778e6e7eaa21791cd364625"
    verify: True

wallets:
  from_key: ${PRIVATE_KEY}
